### ISSUE TITLE
Unable to complete study

### ISSUE THREAD

**Issue by sahTech1** [christinaread/EHDENUseCase#4]
Hello, we are attempting to run the study, end to end (from downloading the files, to executing in R) and for some reason the code runs and fails in generation all of the cohorts. Instead of creating all 26 cohorts it creates 9 (I checked by querying the database using a query like this:

SELECT
      COUNT(*)                                                       nbrRows   -- about 9k
    , COUNT(distinct cohort_definition_id)            distinct_cohort_definition_id -- 9 ids
    , COUNT(distinct subject_id)                            distinct_subject_id -- ~5k ids
    , COUNT(DISTINCT era_number) --1 result
    , MIN(era_number) -- 1 is the result
    , MAX(era_number) -- 1 is the result
FROM database.mytmp.randomident_cohort_person

Do you happen to know why it would fail and produce this error?  Also, what steps do you recommend I take to resolve this?

----------------------------------------------------------------------------------------------

Here is the error report that is generated:

Thread: Main
Message:  no rows to aggregate
Level:  FATAL
Time:  2022-10-20 20:49:17

Stack trace:
9: h(simpleError(msg, call))
8: .handleSimpleError(function (condition)
{
    if (is(condition, "error")) {
        log("FATA
7: stop("no rows to aggregate")
6: aggregate.data.frame(lhs, mf[-1], FUN = FUN, ...)
5: aggregate.formula(minDate ~ exposureId, minDates, min)
4: Export.R#295: aggregate(minDate ~ exposureId, minDates, min)
3: Export.R#45: exportMetadata(outputFolder = outputFolder, exportFolder = exportFolder, datab
2: Main.R#187: exportResults(outputFolder = outputFolder, databaseId = databaseId, databaseNam
1: execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohor

R version:
R version 4.1.3 (2022-03-10)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- EHDENUseCase4.3 (0.0.1)
- DatabaseConnector (5.0.2)

**Comment by christinaread** [comment]
Hi,

Thank you for trying to run this study! May I ask which hospital or data group you are representing? This error seems to arise when there are no patients in the exposure cohorts...do you definitely have patients with the use of Aspirin, Heparin, Baricitinib, Remdesivir, and Tocilizumab? 

Also, sorry, we have many branches with different versions of the package as we are working through bugs with another hospital. It's possible this code didn't run because it is an experimental version where we have changed several parameters for the covariates. 

Many hospitals in Europe are using only Remdesivir and Tocilizumab and are not using Baricitinib for the treatment of COVID-19. If that is the case for you, can you try running the branch: https://github.com/ohdsi-studies/EhdenCovidUseCase/tree/RemdesivirTocilizumab?

Otherwise, the most updated version of the code with all cohorts is available here: https://github.com/ohdsi-studies/EhdenCovidUseCase/tree/HydratedMinusCriteria1.

I hope that running one of these may solve the issue or allow us to see more easily what is going wrong!

**Comment by sahTech1** [comment]
Hi, 
Thanks for the response.  I am part of a health system in the United States called MedStar Health.  I checked our internal instance of Atlas and it looks like we have patients and records for all of the medications you listed.  I will try and run the HyrdatedMinusCriteria1 and see if I can successfully run the study.  if that doesn't work, I will try the RemdesivirTocilizumab branch.  I will comment later to let you know the status
Thanks!

**Comment by sahTech1** [comment]
Hello, 
Thanks again for pointing me in the right direction.  

I was able to run the  https://github.com/ohdsi-studies/EhdenCovidUseCase/tree/RemdesivirTocilizumab? Study however it appears I don't have enough records/patients to build the control cohorts.  To finish testing my end-to-end run, I am planning on setting synthesizePositiveControls = FALSE in the CodeToRun file to see if I can then create the RShiny output.  

Please let me know if there are other items I should adjust, check or consider.


**RemdesivirTocilizumab Branch note:**
Also when building the environment using the ReadMe file in RemdesivirTocilizumab branch it produces a 404: Not Found message.

My solution was to switch from "https://raw.githubusercontent.com/ohdsi-studies/EHDENUseCase6.1RemToc/main/renv.lock"
to the one in the  HydraMinusCriteria1 branch"https://raw.githubusercontent.com/ohdsi-studies/EhdenCovidUseCase/HydratedMinusCriteria1/renv.lock"

Thanks again!



Error message: 
An error report has been created at  C:\R\output/errorReportR.txt
Error in synthesizePositiveControls(connectionDetails = connectionDetails,  : 
  **Not enough negative controls with sufficent outcome count** to fit outcome model. Found 3 controls with enough outcomes (> 50), but require 5 controls.
In addition: Warning messages:
1: 'MethodEvaluation::injectSignals' is deprecated.
Use 'synthesizePositiveControls' instead.
See help("Deprecated") 
2: In synthesizePositiveControls(connectionDetails = connectionDetails,  :
  The 'oracleTempSchema' argument is deprecated. Use 'tempEmulationSchema' instead.

**Comment by christinaread** [comment]
As far as I know, I think the only adjustment the other center has needed to make was to also turn off the Positive controls synthesis--I think if you try it as such it will hopefully run correctly! 


Thank you for letting me know about the lockfile issue, I'm not sure why that would be happening. I reuploaded the files in hopes that will solve the issue.

**Comment by sahTech1** [comment]
Thanks. I tried to access the lock file in the [ReadMe ](https://github.com/ohdsi-studies/EhdenCovidUseCase/blob/RemdesivirTocilizumab/README.md) and I am still running into the issue.  Is there a different URL I should use in the code below?

Current code with URL:
install.packages("renv")
download.file("https://raw.githubusercontent.com/ohdsi-studies/EHDENUseCase6.1RemToc/main/renv.lock", "renv.lock")
renv::init()

Thanks!
Stephen

**Comment by christinaread** [comment]
Hi, 

Thank you for pointing that out! The url should be: https://github.com/ohdsi-studies/EhdenCovidUseCase/blob/RemdesivirTocilizumab/renv.lock

(it is now updated in the Readme file as well)

**Comment by sahTech1** [comment]
Thanks again for the help and all the updates!  I think the technical issues are solved and now it looks like I am having issues with having records that match the cohort criteria.  I am going to close this issue and see if I can troubleshoot why I am getting this message.

Error in aggregate.data.frame(lhs, mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate

**Comment by christinaread** [comment]
Are you able to generate any results files, or the larger log file? If you send any output you get to christinaread@nice.org.uk I can try to help troubleshoot from the log file!

**Comment by sahTech1** [comment]
Thanks for the note.  Today we manually imported and ran the JSON cohorts from the study into our Atlas instance to check to see if we had records in each of the cohorts.  While doing this we identified that we are coding Oxygen in the Device domain, whereas the cohorts have it as in the drug domain cause several of the cohorts to filter out all records.  

Do you know of a best practice within the OHDSI CDM for how best to model oxygen delivery or if there was a particular decision on using the drug domain for this study?  The reason I ask is that we are working though QA'ing our the data in the CDM and are wondering if we need to update the ETL to best match the rest of the community?

As for next steps, I am going to try and manually modify the cohorts that have oxygen as a drug in them to also include oxygen as device and then re-run the study to see if I can get it to generate the rshiny app.

Cheers!
Stephen

**Comment by christinaread** [comment]
Hi,

That is interesting--I'm not sure how 0's in the oxygen cohorts would cause such an error if there were populations for the other cohorts. For the other cohorts, did you have matching records for everything? Maybe then it is one of the exclusion criterias that is causing the empty cohorts and thus aggregation issue.

"Oxygen" as a drug exposure was used to define patient receiving oxygen in this study. Since oxygen is included in ATLAS as a drug, it made sense to include it as a drug, but I see now others have also used wider definitions that include things such as "Patient on Oxygen" as a condition as well. I will update the oxygen patient definition in this study to reflect the wider definition, thank you for raising this!

It also seems there was some discussion about encoding oxygen as a drug vs device: https://forums.ohdsi.org/t/conventions-on-storing-ventilation-data/12479, but I would recommend posting on the forum if you are still wondering which to do to match the community.

Best,
Christina

**Comment by sahTech1** [comment]
Hi thank you for the background and suggestions! I will review the forums and get up to speed on the drug vs. device conversation.

As for the other cohorts.  None of the cohorts generated any matches even though they had people and records:
Cohort 1779686.json (people: 76,318 / records: 137,099)
Cohort 1779685.json (people: 154,987 / records: 220,457) 
Cohort 1779684.json (people: 397,866 / records: 397,866) 
Cohort 1779682.json (people: 98,825 / records: 126,595)
Cohort 1779681.json (people: 0/ records: ...)
Cohort 1779680.json (people: 46,862 / records: 46,862)

I emailed the R log file and a cohort report generation summary (screenshots of the reports in the Atlas generation tab) 

Thanks!

**Comment by christinaread** [comment]
Sorry, could you send the email to christina.read@nice.org.uk? I missed a decimal earlier and the other address does not exist!

**Comment by christinaread** [comment]
The cohorts here align with the outcomes, but could you also try the JSONs for the exposure cohorts? 

These are the labels for all the cohorts: 
Target ID	Target Name
1780471	Aspirin Cohort
1780473	Aspirin Cohort Intensive Services 
1780477	Aspirin Cohort Oxygen Users
1780479	Aspirin Cohort Receiving Corticosteroids
1780482	Baricitinib Cohort
1780484	Baricitinib Cohort Intensive Services 
1780486	Baricitinib Cohort Oxygen Users 
1780488	Baricitinib Cohort Receiving Corticosteroids
1780489	Remdesivir Cohort
1780491	Remdesivir Cohort Oxygen Users 
1780490	Remdesivir Intensive Services
1780492	Remdesivir Cohort Receiving Corticosteroids
1780472	Heparin Cohort
1780474	Heparin Cohort Intensive Services 
1780478	Heparin Cohort Oxygen Users
1780480	Heparin Cohort Receiving Corticosteroids
1780481	Tocilizumab Cohort
1780483	Tocilizumab Cohort Intensive Services
1780485	Tocilizumab Cohort Oxygen Users 
1780487	Tocilizumab Cohort Receiving Corticosteroids

**Comment by sahTech1** [comment]
Hello, 
Using NotePad++ I searched the project folder for all of the following JSON recommended and it appears I am missing the following files from my project files:

Missing from project folder:
Target ID Target Name
1780471 Aspirin Cohort
1780473 Aspirin Cohort Intensive Services
1780477 Aspirin Cohort Oxygen Users
1780479 Aspirin Cohort Receiving Corticosteroids
1780482 Baricitinib Cohort
1780484 Baricitinib Cohort Intensive Services
1780486 Baricitinib Cohort Oxygen Users
1780488 Baricitinib Cohort Receiving Corticosteroids
1780472 Heparin Cohort  
1780474 Heparin Cohort Intensive Services
1780478 Heparin Cohort Oxygen Users
1780480 Heparin Cohort Receiving Corticosteroids

Here are the cohorts I did find.
The were saved in > inst/cohorts

Found -> Target ID Target Name PatientsCount
Found -> 1780489 Remdesivir Cohort 3511
Found -> 1780491 Remdesivir Cohort Oxygen Users 0
Found -> 1780490 Remdesivir Intensive Services 512
Found -> 1780492 Remdesivir Cohort Receiving Corticosteroids 853
Found -> 1780481 Tocilizumab Cohort 371
Found -> 1780483 Tocilizumab Cohort Intensive Services 187
Found -> 1780485 Tocilizumab Cohort Oxygen Users 0
Found -> 1780487 Tocilizumab Cohort Receiving Corticosteroids 92

Thanks!
